# Generated by Django 4.2.6 on 2023-10-18 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
                ('status_color', models.CharField(default='#a5a5a5', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subSector_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_url', models.CharField(default='default.css', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('number_w', models.IntegerField(default=0, null=True)),
                ('name_w', models.CharField(max_length=124, null=True)),
                ('observation_w', models.CharField(default='', max_length=124)),
                ('establishment_w', models.ManyToManyField(to='app_efetivos.establishment')),
                ('position_w', models.ManyToManyField(to='app_efetivos.position')),
                ('sector_w', models.ManyToManyField(to='app_efetivos.sector')),
                ('shift_w', models.ManyToManyField(to='app_efetivos.shift')),
                ('status_w', models.ManyToManyField(default='', to='app_efetivos.status')),
                ('subSector_w', models.ManyToManyField(to='app_efetivos.sub_sector')),
            ],
        ),
        migrations.CreateModel(
            name='Global_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_title', models.CharField(default='Estabelecimento', max_length=50)),
                ('sector_title', models.CharField(default='Setor', max_length=50)),
                ('subSector_title', models.CharField(default='Subsetor', max_length=50)),
                ('shift_title', models.CharField(default='Turno', max_length=50)),
                ('position_title', models.CharField(default='Cargo', max_length=50)),
                ('status_title', models.CharField(default='Status', max_length=50)),
                ('logo_image', models.ImageField(default='logos/logo.png', upload_to='logos/')),
                ('bg_image', models.ImageField(default='bgs/bg.png', upload_to='bgs/')),
                ('institution_name', models.CharField(default='Sua Empresa', max_length=60)),
                ('theme', models.ManyToManyField(to='app_efetivos.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard_Presets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=50)),
                ('preset_sectors', models.ManyToManyField(to='app_efetivos.sector')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('preset', models.ManyToManyField(to='app_efetivos.dashboard_presets')),
                ('sector', models.ManyToManyField(to='app_efetivos.sector')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
