# Generated by Django 4.2.5 on 2023-10-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0002_preset_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset_settings',
            name='sector_position',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='preset_settings',
            name='sector_width',
            field=models.IntegerField(default='0'),
        ),
    ]
