# Generated by Django 4.2.5 on 2023-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0005_alter_preset_settings_sector_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset_settings',
            name='sector_position',
            field=models.IntegerField(unique=True),
        ),
    ]
