# Generated by Django 4.2.5 on 2023-10-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0006_alter_preset_settings_sector_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset_settings',
            name='sector_position',
            field=models.IntegerField(default=0),
        ),
    ]
