# Generated by Django 4.2.5 on 2023-10-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_position', models.IntegerField(null=True)),
                ('sector_width', models.IntegerField(null=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_efetivos.dashboard_presets')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_efetivos.sector')),
            ],
        ),
    ]
