# Generated by Django 4.2.5 on 2024-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0008_preset_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_settings',
            name='bg_image',
            field=models.ImageField(default='bgs/bg.png', upload_to='bgs/uploaded_bgs{}'),
        ),
        migrations.AlterField(
            model_name='global_settings',
            name='logo_image',
            field=models.ImageField(default='logos/logo.png', upload_to='logos/uploaded_logo{}'),
        ),
    ]
