# Generated by Django 4.2.5 on 2024-01-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0009_alter_global_settings_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_settings',
            name='bg_image',
            field=models.ImageField(default='bgs/bg.png', upload_to='bgs/uploaded_bgs'),
        ),
        migrations.AlterField(
            model_name='global_settings',
            name='logo_image',
            field=models.ImageField(default='logos/logo.png', upload_to='logos/uploaded_logo'),
        ),
        migrations.CreateModel(
            name='Worker_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_h', models.CharField(max_length=124, null=True)),
                ('observation_h', models.CharField(max_length=124, null=True)),
                ('date_h', models.DateField(null=True)),
                ('id_worker_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_efetivos.worker')),
            ],
        ),
    ]
