# Generated by Django 4.2.5 on 2024-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_efetivos', '0010_alter_global_settings_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_history',
            name='status_color_h',
            field=models.CharField(default='#a5a5a5', max_length=50),
        ),
    ]
